version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: numba
    versions:
    - 0.53.0
  - dependency-name: pymatgen
    versions:
    - 2021.3.3
    - 2021.3.4
    - 2022.0.3
    - 2022.0.4
  - dependency-name: tabulate
    versions:
    - 0.8.8
  - dependency-name: numpy
    versions:
    - 1.20.0
