# general settings
scattering_type: [IMP, ADP]
doping: [-1.99e14, -2.20e15, -1.72e16, -1.86e17, -1.46e18, -4.39e18]
temperatures: [300]
bandgap: 1.14

# electronic_structure settings
interpolation_factor: 50

# materials properties
deformation_potential: [6.5, 8.1]
elastic_constant: 144
static_dielectric: [[11.7, 0, 0], [0, 11.7, 0], [0, 0, 11.7]]
high_frequency_dielectric: [[11.7, 0, 0], [0, 11.7, 0], [0, 0, 11.7]]

# performance settings
write_mesh: true
