name: Merge dependencies

on:
  workflow_run:
    workflows: ["Build documentation", "Run tests"]
    types:
      - completed

jobs:
  merge-deps:
    needs:
      - lint
      - test
      - docs
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}